<?php


namespace ElveCz\MysqlToElasticSearch\Infrastructure\Commands;


use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class MakeMappingCommand extends Command
{

    protected function configure()
    {
        $this
            ->setName('make:elasticsearch:mapping')
            ->setDescription('Creates an elasticsearch mapping for mysql table.');

        parent::configure(); // TODO: Change the autogenerated stub
    }


    protected function execute(InputInterface $input, OutputInterface $output)
    {
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }


}